apiVersion: apps/v1
kind: Deployment
metadata:
  name: gooddeployment-disallow-default
  labels:
    app: nginx2
  namespace: kyverno-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - image: docker.io/nginxinc/nginx-unprivileged:1.21
        name: nginx2
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
