apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-deployment-restrict-image
  labels:
    app: nginx7
  namespace: kyverno-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx7
  template:
    metadata:
      labels:
        app: nginx7
    spec:
      containers:
      - image: docker.io/nginxinc/nginx-unprivileged:1.21   #registry.k8s.io/nginx:1.7.9
        ports:
        - containerPort: 8080  
        name: nginx7
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service7
spec:
  selector:
    app: nginx7
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
