apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-deployment-limits
  labels:
    app: nginx6
  namespace: kyverno-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx6
  template:
    metadata:
      labels:
        app: nginx6
    spec:
      containers:
      - image: docker.io/nginxinc/nginx-unprivileged:1.21
        name: nginx6
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service6
spec:
  selector:
    app: nginx6
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
